#!/usr/bin/env bash
# Build AnchorApp + AnchorHelper via SPM, then assemble Anchor.app bundle.
#
# Output: build/Anchor.app
#
# Usage:
#   ./Scripts/build-app.sh [release|debug]   (default: release)
set -euo pipefail

CONFIG="${1:-release}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "==> swift build --configuration ${CONFIG} (arm64-only)"
swift build --configuration "${CONFIG}" --arch arm64

BIN_DIR="$(swift build --configuration "${CONFIG}" --arch arm64 --show-bin-path)"
APP="${ROOT}/build/Anchor.app"

echo "==> Assembling .app bundle at ${APP}"
rm -rf "${APP}"
mkdir -p "${APP}/Contents/MacOS"
mkdir -p "${APP}/Contents/Resources"
mkdir -p "${APP}/Contents/Library/LaunchAgents"
mkdir -p "${APP}/Contents/Library/LaunchDaemons"

# Main executable
cp "${BIN_DIR}/AnchorApp" "${APP}/Contents/MacOS/AnchorApp"

# Helper executable, embedded as a LaunchAgent program
cp "${BIN_DIR}/AnchorHelper" "${APP}/Contents/MacOS/AnchorHelper"

# Privileged daemon executable — installed as a LaunchDaemon (root)
# via SMAppService.daemon from AnchorApp's first launch.
cp "${BIN_DIR}/AnchorPrivilegedDaemon" "${APP}/Contents/MacOS/AnchorPrivilegedDaemon"

# Info.plist + entitlements live alongside the app source; copy in
cp "${ROOT}/Sources/AnchorApp/Resources/Info.plist" "${APP}/Contents/Info.plist"

# App icon (.icns). Regenerated by Scripts/generate-icon.swift when
# missing or when the AnchorGlyph source changes.
if [[ -f "${ROOT}/Sources/AnchorApp/Resources/AppIcon.icns" ]]; then
  cp "${ROOT}/Sources/AnchorApp/Resources/AppIcon.icns" "${APP}/Contents/Resources/AppIcon.icns"
fi
cp "${ROOT}/Sources/AnchorHelper/Resources/LaunchAgent.plist" "${APP}/Contents/Library/LaunchAgents/app.anchor.mac.helper.plist"
cp "${ROOT}/Sources/AnchorPrivilegedDaemon/Resources/LaunchDaemon.plist" "${APP}/Contents/Library/LaunchDaemons/app.anchor.mac.privileged-helper.plist"

# Helper / daemon Info.plists sit inside Contents/Library, referenced by
# SMAppService.agent and SMAppService.daemon respectively.

# NOTE: We do NOT run appintentsmetadataprocessor here. It requires
# `.swiftconstvalues` files emitted by the Swift compiler per source file,
# which SPM doesn't produce. To enable AppIntents discovery (Shortcuts /
# Spotlight) we need to either (a) migrate to .xcodeproj or (b) build a
# custom per-file Swift invocation that emits const values. Tracked in
# spikes/SPIKE_REPORT.md spike 8. The AppIntent code in
# Sources/AnchorApp/AnchorIntents.swift is real and ships in the binary;
# it just isn't surfaced to the system yet.

echo "==> Bundle assembled."
ls -la "${APP}/Contents/MacOS/"
echo ""
echo "Next:  ./Scripts/sign.sh         to codesign the bundle"
echo "       ./Scripts/notarize.sh     to submit for notarisation"
echo "       open ${APP}               to run locally"
